from __future__ import annotations

from typing import Any


DEFAULT_CONFIG: dict[str, Any] = {
    "slip_hidden": 128,
    "slip_blocks": 5,
    "friction_hidden": 48,
    "friction_blocks": 4,
    "dropout": 0.05,
    "mu_0": 0.6,
    "V_0": 1e-9,
    "sigma_n": 100e6,
    "lambda_data": 1.0,
    "lambda_data_position": 1.0,
    "lambda_data_velocity": 0.03,
    "lambda_rsf": 0.3,
    "lambda_state": 0.1,
    "lambda_smooth": 1e-3,
    "surface_velocity_scale": 1e-8,
    "position_huber_beta": 5e-3,
    "velocity_huber_beta": 1.0,
    "position_component_weights": (1.0, 1.0, 1.0),
    "velocity_component_weights": (1.0, 1.0, 1.0),
    "total_steps": 20_000,
    "lr": 1e-4,
    "lr_min": 1e-5,
    "weight_decay": 1e-4,
    "grad_clip": 1.0,
    "data_batch_size": 24,
    "n_colloc_per_step": 6,
    "time_ranges_data": [(2020, 2024)],
    "time_domain_physics": (2020, 2024),
    "reference_date": "2020-01-01",
    "log_every": 200,
    "tau_dot_init": 0.1,
    "time_input_scale": 1e8,
    "gap_min_days": 0.5,
    "gap_max_days": 1.5,
    "apply_robust_filter": True,
    "mad_scale": 1.4826,
    "mad_sigma_threshold": 8.0,
    "inversion_sigma_threshold": 6.0,
    "inversion_ratio_min": 0.6,
    "inversion_cancellation_max": 0.45,
    "slope_window_days": 14.0,
    "slope_min_points": 10,
    "savgol_window": 21,
    "savgol_polyorder": 3,
    "excluded_markers": ("UNOV00ITA", "GVNL00ITA", "TOD200ITA"),
    "excluded_markers_subdir": "None",
    "max_station_jump_m": None,
    "warmup_start": 2_000,
    "warmup_end": 8_000,
    "lambda_friction_reg": 0.05,
    "target_ab_mean": 0.0,
    "target_ab_std": 0.008,
    "lambda_V_temporal": 1e-3,
    "geo_weight_enabled": True,
    "geo_weight_k": 5,
    "geo_weight_alpha": 0.5,
    "geo_weight_clip_min": 0.5,
    "geo_weight_clip_max": 2.0,
    "stations_json": "dataset_scremato/stations_ITA_laquila_150km.json",
}
